AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: CD Demo Lambda
Resources:
  CDDemoLambda1:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: hw2-search-photos
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./hw2-search-photos
      Description: "Lambda function for CD Demo"
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::625543281468:role/admin-lambda-role"
      Environment:
        Variables:
          REGION: us-east-1
  CDDemoLambda2:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: hw2-index-photos
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./hw2-index-photos
      Description: "Lambda function for CD Demo"
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::625543281468:role/admin-lambda-role"
      Environment:
        Variables:
          REGION: us-east-1
